CREATE TABLE role(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
);

INSERT INTO `role`(`nome`) VALUES ('LEITURA_ESCRITA');
INSERT INTO `role`(`nome`) VALUES ('ADMINISTRADOR');

